version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
            bundle update capistrano
      - run:
            bundle install --full-index
      - run: node --version
      - run: yarn --version
      - run: yarn install

      - run:
          name: RSpec
          command: bundle exec rspec
          no_output_timeout: 1h
